name: Rust

on:
  push:
    tags: "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          default: true

      - name: Build
        run: |
         cargo build --release &&
          mkdir -pv etcddata-${GITHUB_REF_NAME}-${RUNNER_OS}-${RUNNER_ARCH} && 
          cp target/release/etcddata etcddata-${GITHUB_REF_NAME}-${RUNNER_OS}-${RUNNER_ARCH} -v && 
          tar czvf etcddata-${GITHUB_REF_NAME}-${RUNNER_OS}-${RUNNER_ARCH}.tar.gz etcddata-${GITHUB_REF_NAME}-${RUNNER_OS}-${RUNNER_ARCH}

      - name: Upload Github Assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: target/release/*
          prerelease: ${{ contains(github.ref, '-') }}
